In [5]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
response=requests.get(url)
print(response.status_code)
data=response.json()
print(json.dumps(data,indent=5))

200
{
     "userId": 1,
     "id": 1,
     "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
     "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

In [8]:
print(response.json())
print(type(response.json()))

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
<class 'dict'>

In [9]:
print(response.text)
print(type(response.text))

{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}
<class 'str'>

In [31]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts"
response=requests.get(url)
print(response.status_code)
data=response.json()
#print(json.dumps(data,indent=5))

200

In [12]:
for i in data[:5]:
    print(i['id'],"-",i['title'])

1 - sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2 - qui est esse
3 - ea molestias quasi exercitationem repellat qui ipsa sit aut
4 - eum et est occaecati
5 - nesciunt quas odio

In [15]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts"
params={'userId':1}
response=requests.get(url,params=params)
print(response.status_code)
data=response.json()
print(len(data))
#print(json.dumps(data,indent=5))

200
10

In [16]:
response.url

'https://jsonplaceholder.typicode.com/posts?userId=1'

In [18]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
headers={"User-Agent":"Mozilla/5.0","Accept":"application/json"}
response=requests.get(url,headers=headers)
print(response.status_code)
data=response.json()
print(json.dumps(data,indent=5))

200
{
     "userId": 1,
     "id": 1,
     "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
     "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

In [23]:
response.headers

{'Date': 'Sat, 30 May 2026 06:26:45 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Cache-Control': 'max-age=43200', 'Etag': 'W/"124-yiKdLzqO5gfBrJFrcdJ8Yq0LGnU"', 'Expires': '-1', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Pragma': 'no-cache', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=dbCqOIPBwxSqrPnuso%2FeBjObB28xbhgoUomDckspVz0%3D\\u0026sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d\\u0026ts=1772009795"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=dbCqOIPBwxSqrPnuso%2FeBjObB28xbhgoUomDckspVz0%3D&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&ts=1772009795"', 'Server': 'cloudflare', 'Vary': 'Origin, Accept-Encoding', 'Via': '2.0 heroku-router', 'X-Content-Type-Options': 'nosniff', 'X-Powered-By': 'Express', 'X-Ratelimit-Limit': '1000', 'X-Ratelimit-Remaining': '999', 'X-Ratelimit-Reset': '1772009800', 'Age': '16884', 'Cf-Cache-Status': 'HIT', 'Content-Encoding': 'zstd', 'CF-RAY': 'a03bab4a2b9426a7-BOM', 'alt-svc': 'h3=":443"; ma=86400'}

In [22]:
response.headers['Date']

'Sat, 30 May 2026 06:26:45 GMT'

In [25]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts"
new_post={
    'title':"Learning requests",
    'body':'This is tutorial',
    'userId':1
}
response=requests.post(url,json=new_post)
print(response.status_code)
print(response.json())

201
{'title': 'Learning requests', 'body': 'This is tutorial', 'userId': 1, 'id': 101}

In [27]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
new_post={
    'id':1,
    'title':"Updated Title",
    'body':'Updated body',
    'userId':1
}
response=requests.put(url,json=new_post)
print(response.status_code)
print(response.json())

200
{'id': 1, 'title': 'Updated Title', 'body': 'Updated body', 'userId': 1}

In [28]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
new_post={
    'title':"Updated Title",
}
response=requests.put(url,json=new_post)
print(response.status_code)
print(response.json())

200
{'title': 'Updated Title', 'id': 1}

In [29]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
new_post={
    'title':"Patched Title",
}
response=requests.patch(url,json=new_post)
print(response.status_code)
print(response.json())

200
{'userId': 1, 'id': 1, 'title': 'Patched Title', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [30]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
response=requests.delete(url)
print(response.status_code)
print(response.json())

200
{}

In [32]:
import requests
import json
url="https://picsum.photos/200"
response=requests.get(url)
with open('random_image.jpg','wb') as f:
    f.write(response.content)
print("Image Downloaded")

Image Downloaded

In [35]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
response=requests.get(url)
data=response.json()
with open('post.json','w') as f:
    json.dump(data,f,indent=5)
print("JSON file saved")

JSON file saved

In [36]:
with open('post.json','r') as f:
    load_data=json.load(f)
print(load_data)

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [37]:
import requests
import json
import pandas as pd
url="https://jsonplaceholder.typicode.com/posts"
response=requests.get(url)
data=response.json()
df=pd.DataFrame(data)
df

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

In [52]:
import requests
import json
url="https://jsonplaceholder.typicode.com/users"
response=requests.get(url)
data=response.json()
for i in data:
    name=i['name']
    uname=i['username']
    phone=i['phone']
    email=i['email']
    city=i['address']['city']
    lat=i['address']['geo']['lat']
    lng=i['address']['geo']['lng']

    print(name)
    print(uname)
    print(phone)
    print(email)
    print(city)
    print(lat)
    print(lng)
    print("---------------------------")

Leanne Graham
Bret
1-770-736-8031 x56442
Sincere@april.biz
Gwenborough
-37.3159
81.1496
---------------------------
Ervin Howell
Antonette
010-692-6593 x09125
Shanna@melissa.tv
Wisokyburgh
-43.9509
-34.4618
---------------------------
Clementine Bauch
Samantha
1-463-123-4447
Nathan@yesenia.net
McKenziehaven
-68.6102
-47.0653
---------------------------
Patricia Lebsack
Karianne
493-170-9623 x156
Julianne.OConner@kory.org
South Elvis
29.4572
-164.2990
---------------------------
Chelsey Dietrich
Kamren
(254)954-1289
Lucio_Hettinger@annie.ca
Roscoeview
-31.8129
62.5342
---------------------------
Mrs. Dennis Schulist
Leopoldo_Corkery
1-477-935-8478 x6430
Karley_Dach@jasper.info
South Christy
-71.4197
71.7478
---------------------------
Kurtis Weissnat
Elwyn.Skiles
210.067.6132
Telly.Hoeger@billy.biz
Howemouth
24.8918
21.8984
---------------------------
Nicholas Runolfsdottir V
Maxime_Nienow
586.493.6943 x140
Sherwood@rosamond.me
Aliyaview
-14.3990
-120.7677
---------------------------
Glenna Reichert
Delphine
(775)976-6794 x41206
Chaim_McDermott@dana.io
Bartholomebury
24.6463
-168.8889
---------------------------
Clementina DuBuque
Moriah.Stanton
024-648-3804
Rey.Padberg@karina.biz
Lebsackbury
-38.2386
57.2232
---------------------------

In [57]:
import requests
import json
url="https://jsonplaceholder.typicode.com/users"
response=requests.get(url)
data=response.json()
rows=[]
for i in data:
    name=i['name']
    uname=i['username']
    phone=i['phone']
    email=i['email']
    city=i['address']['city']
    lat=i['address']['geo']['lat']
    lng=i['address']['geo']['lng']
    d={'Name':name,"UserName":uname,"Phone":phone,"email":email,"city":city,"lat":lat,"lon":lng}
    rows.append(d)
df=pd.DataFrame(rows)
df

,Name,UserName,Phone,email,city,lat,lon
0,Leanne Graham,Bret,1-770-736-8031 x56442,Sincere@april.biz,Gwenborough,-37.3159,81.1496
1,Ervin Howell,Antonette,010-692-6593 x09125,Shanna@melissa.tv,Wisokyburgh,-43.9509,-34.4618
2,Clementine Bauch,Samantha,1-463-123-4447,Nathan@yesenia.net,McKenziehaven,-68.6102,-47.0653
3,Patricia Lebsack,Karianne,493-170-9623 x156,Julianne.OConner@kory.org,South Elvis,29.4572,-164.2990
4,Chelsey Dietrich,Kamren,(254)954-1289,Lucio_Hettinger@annie.ca,Roscoeview,-31.8129,62.5342
5,Mrs. Dennis Schulist,Leopoldo_Corkery,1-477-935-8478 x6430,Karley_Dach@jasper.info,South Christy,-71.4197,71.7478
6,Kurtis Weissnat,Elwyn.Skiles,210.067.6132,Telly.Hoeger@billy.biz,Howemouth,24.8918,21.8984
7,Nicholas Runolfsdottir V,Maxime_Nienow,586.493.6943 x140,Sherwood@rosamond.me,Aliyaview,-14.3990,-120.7677
8,Glenna Reichert,Delphine,(775)976-6794 x41206,Chaim_McDermott@dana.io,Bartholomebury,24.6463,-168.8889
9,Clementina DuBuque,Moriah.Stanton,024-648-3804,Rey.Padberg@karina.biz,Lebsackbury,-38.2386,57.2232

In [54]:
json_string='''{
"name":"Alice",
"Age":25
}'''
data=json.loads(json_string)
print(data)
print(type(json_string))
print(type(data))

{'name': 'Alice', 'Age': 25}
<class 'str'>
<class 'dict'>

In [60]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts"
params={
    '_page':3,
    '_limit':5
}
response=requests.get(url,params=params)
data=response.json()
for i in data:
    print(i['id'],"-",i['title'])

11 - et ea vero quia laudantium autem
12 - in quibusdam tempore odit est dolorem
13 - dolorum ut in voluptas mollitia et saepe quo animi
14 - voluptatem eligendi optio
15 - eveniet quod temporibus

In [64]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts"
page=1
while page<=3:
    params={'_page':page,'_limit':10}
    response=requests.get(url,params=params)
    data=response.json()
    for i in data:
        print(i['id'],"-",i['title'])
    page+=1

1 - sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2 - qui est esse
3 - ea molestias quasi exercitationem repellat qui ipsa sit aut
4 - eum et est occaecati
5 - nesciunt quas odio
6 - dolorem eum magni eos aperiam quia
7 - magnam facilis autem
8 - dolorem dolore est ipsam
9 - nesciunt iure omnis dolorem tempora et accusantium
10 - optio molestias id quia eum
11 - et ea vero quia laudantium autem
12 - in quibusdam tempore odit est dolorem
13 - dolorum ut in voluptas mollitia et saepe quo animi
14 - voluptatem eligendi optio
15 - eveniet quod temporibus
16 - sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio
17 - fugit voluptas sed molestias voluptatem provident
18 - voluptate et itaque vero tempora molestiae
19 - adipisci placeat illum aut reiciendis qui
20 - doloribus ad provident suscipit at
21 - asperiores ea ipsam voluptatibus modi minima quia sint
22 - dolor sint quo a velit explicabo quia nam
23 - maxime id vitae nihil numquam
24 - autem hic labore sunt dolores incidunt
25 - rem alias distinctio quo quis
26 - est et quae odit qui non
27 - quasi id et eos tenetur aut quo autem
28 - delectus ullam et corporis nulla voluptas sequi
29 - iusto eius quod necessitatibus culpa ea
30 - a quo magni similique perferendis

In [66]:
import requests
url="https://jsonplaceholder.typicode.com/posts"
token="my_secret_token"
headers={"Authorization":f"Bearer {token}"}
response=requests.get(url,headers=headers)
print(response.status_code)
print(response.json())

200